
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= Rails.application.credentials.dev_password %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: employee_record_development

test:
  <<: *default
  database: employee_record_test

production:
  <<: *default
  database: employee_record_production
  username: employee_record
  password: <%= ENV["EMPLOYEE_RECORD_DATABASE_PASSWORD"] %>
